---
abstract: 'get Weightbot iPhone app data from weightbot.com'
author:
  - 'Ivan Bessarabov <ivan@bessarabov.ru>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Weightbot-API
requires:
  Carp: 0
  Class::Date: 0
  File::Slurp: 0
  WWW::Mechanize: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/bessarabov/Weightbot-API/issues
  homepage: https://github.com/bessarabov/Weightbot-API
  repository: https://github.com/bessarabov/Weightbot-API.git
version: 0.04
