--- #YAML:1.0
name:               Weightbot-API
version:            0.03
abstract:           get Weightbot iPhone app data from weightbot.com
author:
    - Ivan Bessarabov <ivan@bessarabov.ru>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Date:     0
    File::Slurp:     0
    Test::More:      0
    WWW::Mechanize:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
